# Generated by Django 5.2 on 2025-08-23 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('skin_type', models.CharField(blank=True, choices=[('oily', 'Oily'), ('dry', 'Dry'), ('sensitive', 'Sensitive'), ('combination', 'Combination')], max_length=50, null=True)),
                ('concerns', models.JSONField(default=list)),
                ('preferences', models.JSONField(default=list)),
                ('device_type', models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('cleanser', 'Cleanser'), ('serum', 'Serum'), ('moisturizer', 'Moisturizer'), ('toner', 'Toner'), ('sunscreen', 'Sunscreen')], max_length=50)),
                ('skin_types', models.JSONField(default=list)),
                ('concerns_targeted', models.JSONField(default=list)),
                ('ingredients', models.JSONField(default=list)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField(default=0.0)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ContextualData',
            fields=[
                ('context_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_type', models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('season', models.CharField(blank=True, choices=[('winter', 'Winter'), ('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contextual_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BrowsingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('wishlist', 'Wishlist'), ('cart', 'Cart')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('skin_type', models.CharField(choices=[('oily', 'Oily'), ('dry', 'Dry'), ('sensitive', 'Sensitive'), ('combination', 'Combination')], max_length=50)),
                ('concerns', models.JSONField(default=list)),
                ('preferences', models.JSONField(default=list)),
                ('budget_range', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoutinePlan',
            fields=[
                ('routine_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=50)),
                ('steps', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
